CREATE TABLE IF NOT EXISTS profiles (
  owner TEXT PRIMARY KEY,
  slug UUID NOT NULL UNIQUE,
  data JSONB NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS avatars (
  id UUID PRIMARY KEY,
  owner TEXT NOT NULL,
  url TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
