'use client';
import {useState,useEffect,useRef} from 'react';
import {logout} from './auth-actions';
import QRCode from 'qrcode';
import {Link2,Plus,ArrowUpRight,Copy,Check,GripVertical,Trash2,ArrowUp,ArrowDown,Palette,QrCode,Upload,LogOut,Save,Smartphone,ShieldCheck} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Switch} from '@/components/ui/switch';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {emptyProfile,Profile,profileSchema} from '@/lib/profile';
import ProfileView from './profile-view';
export default function Dashboard({signedIn,email,initial,initialSlug,loadError}:{signedIn:boolean,email:string,initial:Profile|null,initialSlug:string,loadError:string}){
 const [p,setP]=useState<Profile>(initial||emptyProfile),[slug,setSlug]=useState(initialSlug),[tab,setTab]=useState('links'),[dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[uploading,setUploading]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(loadError),[origin,setOrigin]=useState(''),[qr,setQr]=useState(''),[remove,setRemove]=useState<string|null>(null);const drag=useRef<number|null>(null);
 const url=slug&&origin?origin+'/p/'+slug:'';
 useEffect(()=>setOrigin(window.location.origin),[]);
 useEffect(()=>{if(!url)return;let active=true;QRCode.toDataURL(url,{width:1024,margin:4,errorCorrectionLevel:'M',color:{dark:'#111827',light:'#ffffff'}}).then(v=>{if(active)setQr(v)}).catch(()=>setError('De QR-code kon niet worden gemaakt. Probeer opnieuw.'));return()=>{active=false}},[url]);
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn)},[dirty]);
 function update(v:Partial<Profile>){setP(old=>({...old,...v}));setDirty(true);setMessage('');}
 function link(id:string,v:Partial<Profile['links'][number]>){update({links:p.links.map(l=>l.id===id?{...l,...v}:l)})}
 function move(from:number,to:number){if(to<0||to>=p.links.length||from===to)return;const list=[...p.links];list.splice(to,0,list.splice(from,1)[0]);update({links:list})}
 async function save(){setError('');setMessage('');const check=profileSchema.safeParse(p);if(!check.success){setError(check.error.issues[0].message);setTab('links');return;}setBusy(true);try{const r=await fetch('/api/profile',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(check.data)});const d=await r.json() as {error?:string,slug:string};if(!r.ok)throw new Error(d.error);setSlug(d.slug);setP(check.data);setDirty(false);setMessage('Opgeslagen. Je openbare pagina is bijgewerkt.');}catch(e){setError(e instanceof Error?e.message:'Opslaan is niet gelukt.');}finally{setBusy(false)}}
 async function upload(file?:File){if(!file)return;setUploading(true);setError('');try{const fd=new FormData();fd.append('file',file);const r=await fetch('/api/avatar',{method:'POST',body:fd});const d=await r.json() as {error?:string,url:string};if(!r.ok)throw new Error(d.error);update({avatar:d.url});}catch(e){setError(e instanceof Error?e.message:'Upload mislukt.')}finally{setUploading(false)}}
 async function copy(){try{await navigator.clipboard.writeText(url);setMessage('Paginalink gekopieerd.');}catch{setError('Kopiëren lukt niet. Selecteer en kopieer de paginalink hieronder.');}}
 async function download(format:'png'|'svg'){try{let href=qr;if(format==='svg'){const svg=await QRCode.toString(url,{type:'svg',margin:4,errorCorrectionLevel:'M',color:{dark:'#111827',light:'#ffffff'}});href=URL.createObjectURL(new Blob([svg],{type:'image/svg+xml'}));}const a=document.createElement('a');a.href=href;a.download='linkplek-qr.'+format;a.click();if(format==='svg')setTimeout(()=>URL.revokeObjectURL(href),1000);}catch{setError('Download mislukt. Probeer het opnieuw.');}}
 return <div className="app-shell"><header className="topbar"><a className="wordmark" href="/"><span className="brand-icon"><Link2 size={25}/></span>linkplek<span className="brand-period">.</span></a><span className="workspace-label">Jouw persoonlijke linkpagina</span><div className="account">{signedIn?<><span className="account-email">{email}</span><form action={logout}><button type="submit" className="icon-button" aria-label="Uitloggen"><LogOut size={19}/></button></form></>:<a className="button small" href="/inloggen" target="_top">Inloggen met Google <ArrowUpRight size={16}/></a>}</div></header>
 <main className="workspace"><div className="page-heading"><div><div className="eyebrow">JOUW PLEK OP HET WEB</div><h1>Alles begint met één link.</h1><p>Maak het persoonlijk. Voeg je links toe. Deel je wereld.</p></div>{signedIn?<button className="button primary" onClick={save} disabled={busy||uploading||!!loadError}><Save size={18}/>{busy?'Opslaan…':'Wijzigingen opslaan'}</button>:<a className="button primary" href="/inloggen" target="_top">Maak je eigen pagina <ArrowUpRight size={18}/></a>}</div>
 {!signedIn&&<div className="signin-note"><ShieldCheck size={19}/><span>Log in met Google om je eigen pagina te maken en je links te bewaren. Je bezoekers hoeven niet in te loggen.</span></div>}
 <div aria-live="polite">{error&&<div className="notice error" role="alert">{error}</div>}{message&&<div className="notice success"><Check size={18}/>{message}</div>}</div>
 <div className="editor-grid"><section className="editor"><Tabs value={tab} onValueChange={setTab}><TabsList className="editor-tabs" variant="line"><TabsTrigger value="links"><Link2/>Mijn links</TabsTrigger><TabsTrigger value="design"><Palette/>Vormgeving</TabsTrigger><TabsTrigger value="qr"><QrCode/>QR-code & delen</TabsTrigger></TabsList>
 <fieldset disabled={busy||!!loadError} className="editor-fields"><TabsContent value="links"><div className="section-heading"><div><h2>Dit ben jij</h2><p>Een herkenbare eerste indruk.</p></div><span className="step-label">01 / PROFIEL</span></div><div className="card profile-editor"><div className="photo-row"><div className="small-avatar">{p.avatar?<img src={p.avatar} alt="Je profielfoto"/>:(p.title||'J').slice(0,1).toUpperCase()}</div><div><label className={'button small upload '+(!signedIn?'disabled':'')}><Upload size={16}/>{uploading?'Uploaden…':'Foto of logo uploaden'}<input type="file" accept="image/png,image/jpeg,image/webp" disabled={!signedIn||uploading} onChange={e=>{upload(e.target.files?.[0]);e.target.value=''}}/></label><p className="hint">JPG, PNG of WebP · maximaal 2 MB</p>{p.avatar&&<button className="text-button" onClick={()=>update({avatar:''})}>Foto verwijderen</button>}</div></div><label className="field">Naam of titel<input maxLength={80} value={p.title} onChange={e=>update({title:e.target.value})} placeholder="Bijvoorbeeld: Studio Noord"/></label><label className="field">Korte beschrijving<textarea maxLength={240} rows={2} value={p.bio} onChange={e=>update({bio:e.target.value})} placeholder="Vertel in een paar woorden wie je bent."/><span className="character-count">{p.bio.length}/240</span></label></div>
 <div className="section-heading links-heading"><div><h2>Jouw links <span className="count">{p.links.length}</span></h2><p>Sleep om te sorteren, of gebruik de pijltjes.</p></div><button className="button add" disabled={p.links.length>=50} onClick={()=>update({links:[...p.links,{id:crypto.randomUUID(),title:'',url:'',visible:true}]})}><Plus size={18}/>Link toevoegen</button></div>
 <div className="link-list">{p.links.map((l,i)=><article className={'card link-card '+(!l.visible?'hidden-link':'')} key={l.id} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(drag.current!==null)move(drag.current,i);drag.current=null;}}><div className="link-card-top"><button className="drag-handle icon-button" draggable onDragStart={e=>{drag.current=i;e.dataTransfer.effectAllowed='move';e.dataTransfer.setData('text/plain',String(i));}} onDragEnd={()=>drag.current=null} aria-label={'Versleep '+(l.title||'link')}><GripVertical size={19}/></button><span className="link-number">LINK {String(i+1).padStart(2,'0')}</span><label className="visibility"><span>{l.visible?'Zichtbaar':'Verborgen'}</span><Switch checked={l.visible} onCheckedChange={v=>link(l.id,{visible:v})} aria-label={'Toon '+(l.title||'link')}/></label></div><div className="link-inputs"><label className="field">Titel<input maxLength={100} value={l.title} onChange={e=>link(l.id,{title:e.target.value})} placeholder="Bijvoorbeeld: Mijn website"/></label><label className="field">Webadres<input type="url" value={l.url} onChange={e=>link(l.id,{url:e.target.value})} placeholder="https://jouwwebsite.nl"/></label></div><div className="link-tools"><button className="icon-button" aria-label="Link omhoog" disabled={i===0} onClick={()=>move(i,i-1)}><ArrowUp size={16}/></button><button className="icon-button" aria-label="Link omlaag" disabled={i===p.links.length-1} onClick={()=>move(i,i+1)}><ArrowDown size={16}/></button><button className="icon-button delete" aria-label={'Verwijder '+(l.title||'link')} onClick={()=>setRemove(l.id)}><Trash2 size={16}/></button></div></article>)}{!p.links.length&&<div className="empty-links"><span className="empty-icon"><Link2 size={27}/></span><h3>Een lege pagina, vol mogelijkheden.</h3><p>Je website, socials of nieuwste project.<br/>Voeg je eerste link toe om te beginnen.</p><button className="text-button" onClick={()=>update({links:[{id:crypto.randomUUID(),title:'',url:'',visible:true}]})}><Plus size={16}/>Je eerste link toevoegen</button></div>}</div></TabsContent>
 <TabsContent value="design"><div className="section-heading"><div><h2>Helemaal jouw stijl</h2><p>Je ziet elke aanpassing direct in het voorbeeld.</p></div></div><div className="card design-card"><h3>Kies een startpunt</h3><div className="themes">{[{name:'Kobalt',bg:'#e5ebff',color:'#243eb8'},{name:'Nacht',bg:'#172033',color:'#e0ef9b'},{name:'Fris',bg:'#e2f7f1',color:'#155447'},{name:'Roze',bg:'#fce9f0',color:'#92244e'}].map(t=><button key={t.name} className={'theme '+(p.background===t.bg&&p.color===t.color?'selected':'')} onClick={()=>update({background:t.bg,color:t.color})}><span style={{background:t.bg}}><i style={{background:t.color}}/><i style={{background:t.color}}/><i style={{background:t.color}}/></span>{t.name}</button>)}</div><div className="color-fields"><label className="field">Achtergrond<div className="color-input"><input type="color" value={p.background} onChange={e=>update({background:e.target.value})}/><span>{p.background.toUpperCase()}</span></div></label><label className="field">Knopkleur<div className="color-input"><input type="color" value={p.color} onChange={e=>update({color:e.target.value})}/><span>{p.color.toUpperCase()}</span></div></label></div><h3>Knopstijl</h3><div className="shape-options">{[{id:'round',name:'Rond'},{id:'soft',name:'Afgerond'},{id:'square',name:'Recht'}].map(s=><button key={s.id} aria-pressed={p.shape===s.id} className={p.shape===s.id?'selected':''} style={{borderRadius:s.id==='round'?30:s.id==='soft'?10:2}} onClick={()=>update({shape:s.id as Profile['shape']})}>{s.name}</button>)}</div><p className="hint">De tekstkleur past zich automatisch aan voor leesbaar contrast.</p></div></TabsContent>
 <TabsContent value="qr"><div className="section-heading"><div><h2>Eén scan. Al jouw links.</h2><p>Van visitekaartje tot poster: neem je pagina overal mee.</p></div></div><div className="card qr-card">{url?<><div className="qr-image">{qr?<img src={qr} alt="QR-code naar jouw openbare linkpagina"/>:<p>QR-code genereren…</p>}</div><h3>Jouw QR-code is klaar</h3><p>Dezelfde code. Ook als je links veranderen.</p><div className="download-buttons"><button className="button primary" disabled={!qr} onClick={()=>download('png')}>Download PNG</button><button className="button" disabled={!qr} onClick={()=>download('svg')}>Download SVG</button></div><p className="hint">PNG: 1024 × 1024 pixels · SVG: schaalbaar voor drukwerk</p><label className="field qr-url">Je permanente paginalink<input readOnly value={url} onFocus={e=>e.target.select()}/></label><button className="button" onClick={copy}><Copy size={16}/>Link kopiëren</button></>:<><div className="empty-icon"><QrCode size={40}/></div><h3>Eerst jouw pagina, dan je QR-code</h3><p>Vul je profiel in en sla je pagina op.<br/>Daarna kun je jouw eigen QR-code downloaden.</p><button className="button primary" onClick={()=>setTab('links')}>Naar mijn links</button></>}</div><div className="qr-tip"><ShieldCheck size={22}/><div><strong>Gemaakt om te blijven</strong><p>Je QR-code verwijst naar je vaste pagina. Je kunt je links dus op elk moment aanpassen, zonder opnieuw te printen.</p></div></div></TabsContent></fieldset></Tabs></section>
 <aside className="preview-column"><div className="preview-heading"><span><Smartphone size={17}/>Livevoorbeeld</span><span className="preview-badge">{dirty?'Niet opgeslagen':slug?'Opgeslagen':'Concept'}</span></div><div className="phone"><div className="phone-speaker"/><ProfileView profile={p} preview/></div><p className="preview-caption">Een klein scherm. Jouw hele wereld.</p>{url&&<div className="preview-actions"><a className="button small" href={url} target="_blank" rel="noopener noreferrer">Open pagina<ArrowUpRight size={16}/></a><button className="icon-button" onClick={copy} aria-label="Kopieer paginalink"><Copy size={18}/></button></div>}</aside></div><footer className="app-footer"><span>linkplek. <span>Alles wat je wilt delen.</span></span><span>Gemaakt voor jouw volgende klik.</span></footer></main>
 <AlertDialog open={!!remove} onOpenChange={v=>{if(!v)setRemove(null)}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Link verwijderen?</AlertDialogTitle><AlertDialogDescription>De link verdwijnt uit je concept. Sla daarna je wijzigingen op om je openbare pagina bij te werken.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Annuleren</AlertDialogCancel><AlertDialogAction onClick={()=>{update({links:p.links.filter(l=>l.id!==remove)});setRemove(null)}}>Verwijderen</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></div>
}
